apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::605628033628:role/eksctl-eksctl-demo-nodegroup-ng-0-NodeInstanceRole-LZKG6VCFCBRC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::605628033628:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-03T07:36:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1777"
  uid: 0409a377-72db-4a8b-adb4-6bf94694f0d6
